version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173" 
    env_file:
      - frontend/.env
    environment:
      - VITE_HOST=0.0.0.0  

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"  
    env_file:
      - backend/.env
